### ISSUE TITLE
[BUG] ChatGPT doesn't work anymore. 

### ISSUE THREAD

**Issue by j3sch** [d6u/PromptPlay#99] opened 2024-02-14 12:24 UTC
Hi, I can no longer run ChatGPT chat completion and the border turns red. I created a new test project and replaced my API token, but that also didn't work. The example space don't work either.

Thank you for creating this project, it helps me test my prompt.

**Comment by d6u** [comment] 2024-02-14 17:13
Sorry about the inconvenience. The issue is already fixed on main. But I'm working a couple other features and fixes as well. Will aim to deploy a new front end by this Friday.

**Comment by d6u** [comment] 2024-02-16 03:08
New version of frontend has been deployed. Thanks for giving a try and providing feedbacks!

**Closed by d6u** 2024-02-16 03:08 UTC
Labels: bug
